/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 探活（免鉴权） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            /** Format: int64 */
                            ts: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设备上报状态（响应带回期望状态与配置版本，合并往返） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceReport"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 上报过频 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 拉取配置（仅在 appliedRevision != configRevision 时需要） */
        get: {
            parameters: {
                query: {
                    deviceId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceConfigEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传截图（multipart；meta 为 JSON，file 为图片） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @description JSON 字符串：{"deviceId":"...","ts":1699999999999,"label":"可选"} */
                        meta: string;
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            id: string;
                            /** Format: int64 */
                            ts: number;
                        };
                    };
                };
                /** @description 文件过大 */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 指令回执 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        deviceId: string;
                        commandIds: string[];
                        result?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录（成功下发 HttpOnly 会话 Cookie） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionInfo"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 尝试过频，已退避 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前会话与设备 Token（替代旧的 HTML 占位符注入） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 设备列表 + 总览统计（白名单字段，绝不含任何密钥） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DevicesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 设备详情（含最近上报） */
        get: {
            parameters: {
                query?: {
                    reports?: number;
                };
                header?: never;
                path: {
                    id: components["parameters"]["DeviceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceDetail"];
                    };
                };
                /** @description 设备不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 更新设备的面板侧信息（备注），返回更新后的总览条目 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["DeviceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 面板侧备注；不下发给设备、不影响配置 revision */
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceSummary"];
                    };
                };
                /** @description 设备不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/devices/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 时间序列（在线/轮次/心跳），供曲线用 */
        get: {
            parameters: {
                query?: {
                    from?: number;
                    to?: number;
                    /** @description 采样步长（秒） */
                    step?: number;
                };
                header?: never;
                path: {
                    id: components["parameters"]["DeviceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            points: components["schemas"]["HistoryPoint"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/devices/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 日志检索 */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    q?: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["DeviceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            lines: components["schemas"]["LogLine"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/devices/{id}/interval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 设定该设备的上报周期（下次 report 的 nextReportInMs 生效；0 = 用全局默认） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["DeviceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reportIntervalMs: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            reportIntervalMs?: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/devices/{id}/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 下发启停（写期望状态，设备下次上报执行） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["DeviceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommandRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DesiredState"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/devices/batch-command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量启停 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                        /** @enum {string} */
                        action: "start" | "stop";
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            applied: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/configs/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `default` 或具体 deviceId */
                scope: string;
            };
            cookie?: never;
        };
        /** 读取当前生效配置 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `default` 或具体 deviceId */
                    scope: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigEnvelope"];
                    };
                };
            };
        };
        /** 写入配置（revision 由服务端生成，客户端不得指定） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `default` 或具体 deviceId */
                    scope: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceConfig"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigEnvelope"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/configs/{scope}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 配置历史版本 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            revisions: components["schemas"]["ConfigRevision"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/configs/{scope}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 回滚到某个历史版本（生成新的 revision） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        revision: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/screenshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 截图列表 */
        get: {
            parameters: {
                query?: {
                    deviceId?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            screenshots: components["schemas"]["Screenshot"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/screenshots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 取原图 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 图片字节流 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                    };
                };
                /** @description 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除截图（含磁盘文件） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计日志 */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    actor?: string;
                    target?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries: components["schemas"]["AuditEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全局设置 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        /** 修改全局设置 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE 事件流（report / command / screenshot / device-online / device-offline） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description `text/event-stream`。每个事件形如：
                 *
                 *     ```
                 *     event: report
                 *     data: {"deviceId":"a1b2","ts":1699999999999}
                 *     ```
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Buff: {
            idx: number;
            enabled: boolean;
            key: number;
            /** @description 持续时长（秒）；v0.24.10 起单位由分钟改为秒，默认 280 */
            durationSec: number;
            /** @description 已弃用，仅为兼容旧读者保留（= durationSec/60） */
            durationMin?: number;
        };
        EngineStatus: {
            running?: boolean;
            /** @enum {string} */
            state?: "WAITING" | "CASTING" | "IDLE" | "PAUSED" | "ERROR";
            /** @enum {string} */
            inputMethod?: "keyevent" | "touch";
            cycleCount?: number;
            /**
             * Format: int64
             * @description 设备本地时钟毫秒
             */
            nextDueAt?: number;
            cyclePeriodMs?: number;
            lastResult?: string;
            lastError?: string;
            buffs?: components["schemas"]["Buff"][];
        };
        Heartbeat: {
            batteryPct?: number;
            charging?: boolean;
            thermalC?: number;
            memFreeMb?: number;
            netRttMs?: number;
        };
        DeviceReport: {
            deviceId: string;
            protocolVersion?: number;
            /**
             * Format: int64
             * @description 设备时钟毫秒
             */
            ts: number;
            /** Format: int64 */
            uptimeMs?: number;
            /** Format: int64 */
            versionCode?: number;
            versionName?: string;
            model?: string;
            android?: string;
            targetPkg?: string;
            foreground?: string;
            armed?: boolean;
            appliedRevision?: string;
            engine?: components["schemas"]["EngineStatus"];
            heartbeat?: components["schemas"]["Heartbeat"];
            logTail?: string[];
            ackedCommands?: string[];
        };
        DeviceCommand: {
            id: string;
            /** @enum {string} */
            action: "screenshot";
        };
        DesiredState: {
            running: boolean;
            rev: number;
            /** Format: int64 */
            at?: number;
            by?: string;
        };
        ReportResponse: {
            ok: boolean;
            /** Format: int64 */
            ts: number;
            desired: components["schemas"]["DesiredState"];
            configRevision: string;
            nextReportInMs: number;
            commands?: components["schemas"]["DeviceCommand"][];
        };
        DeviceConfig: {
            /** @description 只读：由服务端生成，PUT 时忽略 */
            revision?: string;
            targetPkg?: string;
            pressMs?: number;
            skillPoints?: number[][];
            /** @enum {string} */
            inputMethod?: "keyevent" | "touch";
            buff?: components["schemas"]["Buff"][];
            notes?: string;
            /** @description 每轮补完 BUFF 后自动进自由市场等待并走到出口待命（回城模式） */
            autoFreeMarket?: boolean;
        };
        DeviceConfigEnvelope: components["schemas"]["DeviceConfig"] & {
            desired?: components["schemas"]["DesiredState"];
        };
        ConfigEnvelope: {
            scope: string;
            revision: string;
            config: components["schemas"]["DeviceConfig"];
            /** Format: int64 */
            updatedAt?: number;
            updatedBy?: string;
        };
        ConfigRevision: {
            revision: string;
            /** Format: int64 */
            createdAt: number;
            createdBy: string;
            config?: components["schemas"]["DeviceConfig"];
        };
        DeviceSummary: {
            id: string;
            /** Format: int64 */
            lastSeen: number;
            /** Format: int64 */
            firstSeen?: number;
            online: boolean;
            model?: string;
            android?: string;
            versionName?: string;
            protocolVersion?: number;
            appliedRevision?: string;
            configRevision?: string;
            configInSync?: boolean;
            group?: string;
            tags?: string[];
            /** @description 面板侧备注（给运维看，不下发给设备、不影响配置 revision） */
            notes?: string;
            reportIntervalMs?: number;
            desired?: components["schemas"]["DesiredState"];
            engine?: components["schemas"]["EngineStatus"];
            heartbeat?: components["schemas"]["Heartbeat"];
            foreground?: string;
            armed?: boolean;
            latestScreenshotId?: string;
            stats?: {
                cycles24h?: number;
                onlineRate24h?: number;
            };
            /**
             * Format: int64
             * @description 上次上报的设备时钟毫秒，用于前端校正时钟偏差
             */
            reportTs?: number;
        };
        DevicesResponse: {
            devices: components["schemas"]["DeviceSummary"][];
            totals: {
                total: number;
                online: number;
                running: number;
                cycles: number;
            };
            defaultConfigRevision?: string;
        };
        ReportRow: {
            /** Format: int64 */
            ts?: number;
            /** Format: int64 */
            receivedAt?: number;
            foreground?: string;
            armed?: boolean;
            running?: boolean;
            state?: string;
            cycleCount?: number;
            batteryPct?: number;
            thermalC?: number;
            netRttMs?: number;
        };
        DeviceDetail: {
            device: components["schemas"]["DeviceSummary"];
            reports?: components["schemas"]["ReportRow"][];
        };
        HistoryPoint: {
            /** Format: int64 */
            ts: number;
            running?: boolean;
            cycleCount?: number;
            batteryPct?: number;
            thermalC?: number;
            netRttMs?: number;
        };
        LogLine: {
            /** Format: int64 */
            ts: number;
            line: string;
        };
        Screenshot: {
            id: string;
            deviceId: string;
            /** Format: int64 */
            ts: number;
            bytes?: number;
            label?: string;
            url: string;
        };
        CommandRequest: {
            /** @enum {string} */
            action: "start" | "stop";
        };
        SessionInfo: {
            ok: boolean;
            user: string;
            /** Format: int64 */
            expiresAt: number;
        };
        Me: {
            user: string;
            deviceToken: string;
            /** Format: int64 */
            expiresAt?: number;
        };
        AuditEntry: {
            id: number;
            /** Format: int64 */
            ts: number;
            actor: string;
            action: string;
            target?: string;
            detail?: string;
            ip?: string;
        };
        Settings: {
            defaultReportIntervalMs: number;
            reportRetentionDays?: number;
            /** @description 设备日志单独保留期；日志比时间序列占地方得多 */
            logRetentionDays?: number;
            screenshotRetentionN?: number;
            screenshotRetentionDays?: number;
        };
    };
    responses: {
        /** @description 未认证或凭据无效 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    ok?: boolean;
                    error?: string;
                };
            };
        };
    };
    parameters: {
        DeviceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
